import { useEffect, useState, type ReactNode } from "react";
import { ShieldAlert } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

function NoticeBody() {
  return (
    <div className="space-y-4 text-sm text-muted-foreground">
      <div>
        <p className="font-medium text-foreground">AI limitations</p>
        <p>
          Responses are generated by a language model. They can be incomplete, outdated, or
          confidently wrong. Treat every output as a first draft, never as legal, financial, HR, or
          medical advice.
        </p>
      </div>
      <div>
        <p className="font-medium text-foreground">Fact-checking is your job</p>
        <p>
          Verify names, numbers, dates, quotes, and commitments against your source material before
          sending an email, publishing a summary, or acting on a plan.
        </p>
      </div>
      <div>
        <p className="font-medium text-foreground">Privacy</p>
        <p>
          Text you submit is sent to an AI provider for processing. This app keeps no account, no
          database, and no server-side copy of your content — drafts live only in your browser
          during the session. Do not paste confidential, regulated, or personal data.
        </p>
      </div>
      <div>
        <p className="font-medium text-foreground">Human accountability</p>
        <p>
          You remain responsible for anything you send or decide based on these outputs. Follow your
          organisation's AI usage policy.
        </p>
      </div>
    </div>
  );
}

export function ResponsibleAiDialog({ children }: { children: ReactNode }) {
  return (
    <Dialog>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ShieldAlert className="size-5 text-accent" /> Responsible AI & privacy notice
          </DialogTitle>
          <DialogDescription>How to use this assistant safely.</DialogDescription>
        </DialogHeader>
        <NoticeBody />
      </DialogContent>
    </Dialog>
  );
}

export function ResponsibleAiGate() {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (localStorage.getItem("ai-notice-ack") !== "1") setOpen(true);
  }, []);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ShieldAlert className="size-5 text-accent" /> Before you start
          </DialogTitle>
          <DialogDescription>
            A quick note on AI limitations, fact-checking, and privacy.
          </DialogDescription>
        </DialogHeader>
        <NoticeBody />
        <DialogFooter>
          <Button
            onClick={() => {
              localStorage.setItem("ai-notice-ack", "1");
              setOpen(false);
            }}
          >
            I understand
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
